name: Build, Publish, and Deploy

on:
  push:
    branches:
      - dev_backend
      - dev_anthony
  pull_request:
    branches:
      - dev_backend
      - dev_anthony

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tony203/inventory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        env:
          URL_DB: ${{ secrets.URL_DB }}
          USER_DB: ${{ secrets.USER_DB }}
          PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
        run: mvn -f ./demo/pom.xml clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest ./demo
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Logout from Docker Hub
        run: docker logout